sudo: required
dist: trusty
language: go
python:
- '2.7'
go:
- 1.8.1
go_import_path: github.com/GoogleCloudPlatform/runtimes-common
jdk:
- oraclejdk8
env:
- NODE_VERSION="6.11.4"
before_install:
- openssl aes-256-cbc -K $encrypted_de21ef459881_key -iv $encrypted_de21ef459881_iv
  -in keys.json.enc -out keys.json -d
- pip install --user --upgrade -r requirements.txt
- nvm install $NODE_VERSION
addons:
  apt:
    sources:
    - sourceline: deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable
        jdk1.8
      key_url: https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg
    packages:
    - bazel
install:
- go get -u github.com/bazelbuild/buildifier/buildifier
- pip install wheel
script:
- "./test.sh"
